version: '3.8'

services:
  autogen:
    build: .
    container_name: autogen-example
    volumes:
      - ./app:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    command: tail -f /dev/null  # Keep container running without executing example
    ports:
      - "8000:8000"  # In case we want to expose any web services
    tty: true        # Allocate a pseudo-TTY
    stdin_open: true # Keep stdin open
    restart: unless-stopped
